# Java中的Runnable与Callable

## 1.概述
自Java诞生以来，多线程已成为该语言的主要方面。 Runnable是提供的代表多线程任务的核心接口，而Callable是Java 1.5中添加的Runnable的改进版本。

在本文中，我们将探讨两个接口的区别和应用。

## 2.执行机制
这两个接口旨在代表可以由多个线程执行的任务。 可运行任务可以使用Thread类或ExecutorService运行，而Callables仅可以使用后者运行。

## 3.返回值
让我们更深入地研究这些接口处理返回值的方式。

### 3.1 与Runnable
Runnable接口是一个功能接口，并且具有单个run（）方法，该方法不接受任何参数并且不返回任何值。

这适用于我们不查找线程执行结果的情况，例如，传入事件记录：

```java
public interface Runnable {
    public void run();
}
```



让我们通过一个例子来理解这一点：

```java
public class EventLoggingTask implements Runnable {
    private Logger logger = LoggerFactory.getLogger(EventLoggingTask.class);

    @Override
    public void run() {

        String messge = "Message read from the event queue";
        logger.info("Message read from event queue is " + messge);

    }
}
```

在此示例中，线程将仅从队列中读取一条消息并将其记录在日志文件中。任务没有返回任何值。可以使用ExecutorService启动任务：

```java
private static ExecutorService executorService;

public static void main(String[] args) {
    executeTask();
}

private static void executeTask() {
    executorService = Executors.newSingleThreadExecutor();

    EventLoggingTask task = new EventLoggingTask();

    Future future = executorService.submit(task);

    executorService.shutdown();
}
```

在这种情况下，Future对象将不包含任何值。

### 3.2 Callable
Callable接口是包含单个call（）方法的泛型接口，该方法返回泛型值V：

```java
public interface Callable<V> {
    V call() throws Exception;
}
```

让我们看一下计算数字的阶乘：

```java
public class FactorialTask implements Callable<Integer> {
    int number;

    public FactorialTask(int number) {
        this.number = number;
    }

    public Integer call() throws InvalidParamaterException {
        int fact = 1;
        if (number < 0)
            throw new InvalidParamaterException("Number must be positive");

        for (int count = number; count > 1; count--) {
            fact = fact * count;
        }

        return fact;
    }

    private class InvalidParamaterException extends Exception {
        public InvalidParamaterException(String message) {
            super(message);
        }
    }
}
```

call（）方法的结果在Future对象中返回：

```java
public class FactorialTaskManualTest {

    private ExecutorService executorService;

    @Before
    public void setup() {
        executorService = Executors.newSingleThreadExecutor();
    }

    @Test
    public void whenTaskSubmitted_ThenFutureResultObtained() throws ExecutionException, InterruptedException {
        FactorialTask task = new FactorialTask(5);
        Future<Integer> future = executorService.submit(task);
        assertEquals(120, future.get().intValue());
    }
    
    @After
    public void cleanup() {
        executorService.shutdown();
    }
}
```

## 4.异常处理
让我们看看它们在异常处理中的适用性。

### 4.1 与Runnable
由于方法签名没有指定“ throws”子句，因此无法传播进一步的检查异常。

### 4.2 与Callable
Callable的call（）方法包含“ throws Exception”子句，因此我们可以轻松地进一步传播已检查的异常：

```java
public class FactorialTask implements Callable<Integer> {
    // ...
    public Integer call() throws InvalidParamaterException {
 
        if(number < 0) {
            throw new InvalidParamaterException("Number should be positive");
        }
    // ...
    }
}
```

如果使用ExecutorService运行Callable，则将在Future对象中收集异常，可以通过调用Future.get（）方法来检查异常。这将引发ExecutionException-包装原始异常：

```java
@Test(expected = ExecutionException.class)
public void whenException_ThenCallableThrowsIt() throws ExecutionException, InterruptedException {
    FactorialTask task = new FactorialTask(-5);
    Future<Integer> future = executorService.submit(task);
    Integer result = future.get().intValue();
}
```

在上面的测试中，当我们传递无效数字时，将引发ExecutionException。我们可以在此异常对象上调用getCause（）方法以获取原始已检查的异常。

如果我们不对Future类的get（）方法进行调用–那么call（）方法抛出的异常将不会被报告回来，并且该任务仍将标记为已完成：

```java
@Test
public void whenException_ThenCallableDoesntThrowsItIfGetIsNotCalled() {
    FactorialTask task = new FactorialTask(-5);
    Future<Integer> future = executorService.submit(task);
    assertEquals(false, future.isDone());
}
```

即使我们为FactorialCallableTask参数的负值引发了异常，上述测试也将成功通过。

## 5.结论
在本文中，我们探讨了Runnable和Callable接口之间的差